# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(default='P', max_length=1)),
                ('door', models.IntegerField(default=0)),
                ('street', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BankInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('branch', models.CharField(max_length=2000)),
                ('address', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='BankMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acct_type', models.CharField(default='SB', max_length=2)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.BankInfo')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('gender', models.CharField(max_length=2)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_type', models.CharField(default='R', max_length=1)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.PersonalInfo')),
            ],
        ),
        migrations.AddField(
            model_name='bankmembership',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.PersonalInfo'),
        ),
        migrations.AddField(
            model_name='bankinfo',
            name='members',
            field=models.ManyToManyField(through='personal.BankMembership', to='personal.PersonalInfo'),
        ),
        migrations.AddField(
            model_name='addressinfo',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.PersonalInfo'),
        ),
    ]
