# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressinfo',
            name='pin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bankinfo',
            name='phone_nbr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bankmembership',
            name='acctnbr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phoneinfo',
            name='phone_nbr',
            field=models.IntegerField(default=0),
        ),
    ]
