# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20170923_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='name',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='first_name',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='last_name',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='middle_name',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='addressinfo',
            name='address_type',
            field=models.CharField(choices=[('P', 'Permanent'), ('T', 'Temporary')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='bankmembership',
            name='acct_type',
            field=models.CharField(choices=[('SB', 'Savings Bank Account'), ('FD', 'Fixed Deposit'), ('RD', 'Recurring Deposit')], default='SB', max_length=2),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2),
        ),
    ]
