# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_auto_20170923_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='emailid',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
