# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_personalinfo_emailid'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='dob',
            field=models.DateField(default=None),
        ),
    ]
