# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_personalinfo_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='dob',
            field=models.DateField(default=None, null=True),
        ),
    ]
