# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 10:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0008_auto_20170928_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='dob',
            field=models.DateField(default=None, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='emailid',
            field=models.CharField(default=None, max_length=500, verbose_name='Email ID'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='first_name',
            field=models.CharField(default=None, max_length=500, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='phoneinfo',
            name='phone_nbr',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='phoneinfo',
            name='phone_type',
            field=models.CharField(choices=[('R', 'Residence'), ('O', 'Office'), ('M', 'Mobile')], default='R', max_length=1, verbose_name='Type'),
        ),
    ]
