# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0009_auto_20170928_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankinfo',
            name='bnk_abbr_name',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='Bank Short Name'),
        ),
        migrations.AddField(
            model_name='bankinfo',
            name='brn_abbr_name',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='Branch Short Name'),
        ),
        migrations.AlterField(
            model_name='addressinfo',
            name='door',
            field=models.IntegerField(default=0, verbose_name='Door #'),
        ),
        migrations.AlterField(
            model_name='addressinfo',
            name='pin',
            field=models.IntegerField(default=0, verbose_name='Pin Code'),
        ),
        migrations.AlterField(
            model_name='addressinfo',
            name='street',
            field=models.CharField(max_length=200, verbose_name='Street Name'),
        ),
        migrations.AlterField(
            model_name='bankinfo',
            name='address',
            field=models.CharField(max_length=2000, verbose_name='Branch Address'),
        ),
        migrations.AlterField(
            model_name='bankinfo',
            name='branch',
            field=models.CharField(default=None, max_length=2000, null=True, verbose_name='Branch Name'),
        ),
        migrations.AlterField(
            model_name='bankinfo',
            name='members',
            field=models.ManyToManyField(through='personal.BankMembership', to='personal.PersonalInfo', verbose_name='Membership between person and bank'),
        ),
        migrations.AlterField(
            model_name='bankinfo',
            name='name',
            field=models.CharField(max_length=2000, verbose_name='Bank Name'),
        ),
        migrations.AlterField(
            model_name='bankinfo',
            name='phone_nbr',
            field=models.IntegerField(default=0, verbose_name='Branch Telephone Number'),
        ),
    ]
