# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0013_auto_20170930_1124'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='phoneinfo',
            unique_together=set([('person', 'phone_type', 'phone_nbr')]),
        ),
    ]
